//! Weight-parity validation for the TimesFM 1.0 200M candle port.
//!
//! Loads the real (converted) safetensors via [`VarBuilder`], reproduces the
//! reference forecast generated by the official PyTorch
//! `PatchedTimeSeriesDecoder` on the SAME input series, and reports concrete
//! error metrics (max-abs-diff, MAE, relative error).
//!
//! Run with:
//! ```ignore
//! cargo run -p timesfm --features candle --example parity -- \
//!     /tmp/timesfm-parity/timesfm.safetensors /tmp/timesfm-parity/ref.json
//! ```
//!
//! Exit code 0 = PASS (within tolerance), 1 = FAIL.

#[cfg(not(feature = "candle"))]
fn main() {
    eprintln!("this example requires --features candle");
    std::process::exit(2);
}

#[cfg(feature = "candle")]
fn main() -> anyhow::Result<()> {
    use candle_core::{DType, Device, Tensor};
    use candle_nn::VarBuilder;
    use serde_json::Value;
    use timesfm::config::TimesfmConfig;
    use timesfm::model::PatchedTimeSeriesDecoder;

    let mut args = std::env::args().skip(1);
    let weights = args
        .next()
        .unwrap_or_else(|| "/tmp/timesfm-parity/timesfm.safetensors".to_string());
    let ref_path = args
        .next()
        .unwrap_or_else(|| "/tmp/timesfm-parity/ref.json".to_string());

    let device = Device::Cpu;

    // --- Load the reference (ground truth). ---
    let ref_raw = std::fs::read_to_string(&ref_path)?;
    let refj: Value = serde_json::from_str(&ref_raw)?;

    let context_len = refj["config"]["context_len"].as_u64().unwrap() as usize;
    let horizon = refj["config"]["horizon"].as_u64().unwrap() as usize;
    let freq_id = refj["config"]["freq_id"].as_u64().unwrap() as u32;

    let input_series: Vec<f32> = refj["input_series"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();
    assert_eq!(input_series.len(), context_len);

    let ref_point: Vec<f32> = refj["point_forecast"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();
    assert_eq!(ref_point.len(), horizon);

    let ref_mu = refj["mu"].as_f64().unwrap() as f32;
    let ref_sigma = refj["sigma"].as_f64().unwrap() as f32;

    // --- Build the candle model from the real weights. ---
    let cfg = TimesfmConfig::timesfm_1p0_200m();
    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[weights.clone()], DType::F32, &device)? };
    let model = PatchedTimeSeriesDecoder::load(cfg.clone(), vb)?;
    eprintln!("loaded candle model from {weights}");

    // --- Run the SAME forecast: context_len series, horizon, freq_id. ---
    let input_ts = Tensor::from_vec(input_series.clone(), (1, context_len), &device)?;
    let input_padding = Tensor::zeros((1, context_len), DType::F32, &device)?;
    let freq = Tensor::from_vec(vec![freq_id], (1, 1), &device)?;

    let (point, _full) = model.decode(&input_ts, &input_padding, &freq, horizon)?;
    let candle_point: Vec<f32> = point.i(0)?.to_vec1()?;
    assert_eq!(candle_point.len(), horizon);

    // --- Compare point forecasts. ---
    // Honesty guard: NaN/Inf in the candle output is an outright FAIL, not a
    // "0 diff". NaN comparisons are false, so we must check explicitly.
    let n_bad = candle_point.iter().filter(|x| !x.is_finite()).count();
    if n_bad > 0 {
        println!("================ TimesFM 1.0 200M PARITY ================");
        println!("candle output has {n_bad}/{horizon} non-finite (NaN/Inf) values.");
        println!("  candle[:5] = {:?}", &candle_point[..5.min(horizon)]);
        println!("VERDICT: FAIL (non-finite candle output)");
        std::process::exit(1);
    }

    let mut max_abs = 0f32;
    let mut sum_abs = 0f64;
    let mut sum_sq = 0f64;
    let mut sum_ref_abs = 0f64;
    let mut argmax = 0usize;
    for (i, (c, r)) in candle_point.iter().zip(ref_point.iter()).enumerate() {
        let d = (c - r).abs();
        if d > max_abs {
            max_abs = d;
            argmax = i;
        }
        sum_abs += d as f64;
        sum_sq += (d as f64) * (d as f64);
        sum_ref_abs += r.abs() as f64;
    }
    let mae = sum_abs / horizon as f64;
    let rmse = (sum_sq / horizon as f64).sqrt();
    // Relative error: L1(diff) / L1(ref) — scale-invariant on the actual signal.
    let rel_err = sum_abs / sum_ref_abs.max(1e-12);

    println!("================ TimesFM 1.0 200M PARITY ================");
    println!("context_len={context_len} horizon={horizon} freq_id={freq_id}");
    println!("ref mu={ref_mu:.6} sigma={ref_sigma:.6}");
    println!();
    println!("point_forecast comparison (candle vs reference torch):");
    println!("  candle[:5]   = {:?}", &candle_point[..5.min(horizon)]);
    println!("  reference[:5]= {:?}", &ref_point[..5.min(horizon)]);
    println!("  candle[-5:]   = {:?}", &candle_point[horizon - 5..]);
    println!("  reference[-5:]= {:?}", &ref_point[horizon - 5..]);
    println!();
    println!("  max-abs-diff = {max_abs:.6e}  (at horizon step {argmax})");
    println!("  MAE          = {mae:.6e}");
    println!("  RMSE         = {rmse:.6e}");
    println!("  rel-error    = {rel_err:.6e}  (L1 diff / L1 ref)");
    println!();

    // Tolerance: target max-abs-diff < 1e-2 (ideally < 1e-3). The reference is
    // f32 torch; candle is f32 — accumulation-order differences put the floor
    // around 1e-4..1e-3 over a 20-layer stack + autoregressive decode.
    let tol = 1e-2f32;
    if max_abs < tol {
        println!("VERDICT: PASS  (max-abs-diff {max_abs:.3e} < tol {tol:.1e})");
        Ok(())
    } else {
        println!("VERDICT: FAIL  (max-abs-diff {max_abs:.3e} >= tol {tol:.1e})");
        // Dump intermediate-tensor norms to aid bisection (see below).
        eprintln!("\nFAIL — see intermediate bisection block to localize divergence.");
        std::process::exit(1);
    }
}

#[cfg(feature = "candle")]
use candle_core::IndexOp;
